---
name: Arduino CI

on: [pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@v0.1.1
        env:
          EXPECT_EXAMPLES: true
          EXPECT_UNITTESTS: true
